server:
  contextPath: /

spring:
  data:
    rest:
      basePath: /api
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://postgres/discooze
    username: postgres
    password: root

jwt:
  header: Authorization
  prefix: Bearer
  secret: bLFAxAFuVczLghCbUb8JfbRq
  expiration: 86400
  allowNoPassword: true

comment:
  image:
    maxDimension: 640

proxy:
  public-base-path: /