server:
  contextPath: /api

spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost/discooze
    username: postgres
    password: root

jwt:
  header: Authorization
  prefix: Bearer
  secret: bLFAxAFuVczLghCbUb8JfbRq
  expiration: 604800
  allowNoPassword: true