server:
  contextPath: /

spring:
  data:
    rest:
      basePath: /api
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres/discooze
    username: postgres
    password: root

jwt:
  header: Authorization
  prefix: Bearer
  secret: bLFAxAFuVczLghCbUb8JfbRq
  expiration: 604800
  allowNoPassword: true